attr:
  source:
    type: url
    url: 'https://download.savannah.nongnu.org/releases/attr/attr-2.5.2.tar.gz'
  source-mirror:
    type: url
    url: 'https://mirror.souseiseki.middlendian.com/nongnu/attr/attr-2.5.2.tar.gz'
  metadata:
    license-files: ['doc/COPYING.LGPL']
    license: LGPL-2.1-or-later

brotli:
  source:
    type: ghtagtar
    repo: google/brotli
    match: 'v1\.\d.*'
  binary: hosted # 等价于v2的provide-pre-built: true
  metadata:
    license-files: ['LICENSE']
    license: MIT

bzip2:
  source:
    type: url
    url: 'https://dl.static-php.dev/static-php-cli/deps/bzip2/bzip2-1.0.8.tar.gz'
  source-mirror:
    type: filelist
    url: 'https://sourceware.org/pub/bzip2/'
    regex: '/href="(?<file>bzip2-(?<version>[^"]+)\.tar\.gz)"/'
  binary: hosted
  metadata:
    license-files: ['{registry_root}/src/globals/licenses/bzip2.txt']
    license: bzip2-1.0.6
