attr:
  type: library
  static-libs@unix:
    - libattr.a
  artifact: attr
brotli:
  type: library
  pkg-configs:
    - libbrotlicommon
    - libbrotlidec
    - libbrotlienc
  headers:
    - brotli
  artifact: brotli
bzip2:
  type: library
  static-libs@unix:
    - libbz2.a
  headers:
    - bzlib.h
  artifact: bzip2

fastlz:
  type: library
  static-libs@unix:
    - libfastlz.a
  headers:
    - fastlz.h
  artifact: fastlz

openssl:
  type: library
  static-libs@unix:
    - libssl.a
    - libcrypto.a
  headers: ['openssl']
  depends:
    - zlib
  artifact: openssl

zlib:
  type: library
  static-libs@unix:
    - libz.a
  headers:
    - zlib.h
    - zconf.h
  artifact: zlib
